In [1]:
import numpy as np

an_array = np.array([3,33,333])

print(type(an_array))

<class 'numpy.ndarray'>


In [2]:
an_array.shape

(3,)

In [3]:
an_array[0] = 888

print(an_array)

[888  33 333]


In [38]:
an_array = np.ones((6,6), dtype=int)

an_array

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [39]:
an_slice = an_array[:2,1:3]

an_slice

array([[1, 1],
       [1, 1]])

In [40]:
print("before", an_array[0, 1])

an_slice[0,0] = 1000

print("after", an_array[0, 1])


before 1
after 1000


In [41]:
an_array[:2,]

array([[   1, 1000,    1,    1,    1,    1],
       [   1,    1,    1,    1,    1,    1]])

In [42]:
col_indices = np.array([0,1,2,3])
row_indices = np.array([1,2,3,0])

for i,j in zip(row_indices, col_indices):
    print(i,", ", j)

1 ,  0
2 ,  1
3 ,  2
0 ,  3


In [43]:
an_array[row_indices,col_indices] += 10000

print(an_array)

[[    1  1000     1 10001     1     1]
 [10001     1     1     1     1     1]
 [    1 10001     1     1     1     1]
 [    1     1 10001     1     1     1]
 [    1     1     1     1     1     1]
 [    1     1     1     1     1     1]]


In [44]:
rand_array = np.random.randn(2,5)

rand_array

array([[ 0.55824343, -1.06048698,  0.04653009, -0.72257849,  0.48645344],
       [-0.23854565, -1.09883063, -1.09033103, -1.46163033, -0.63952221]])

In [46]:
rand_array.mean()

-0.5220698369064269

In [49]:
# compute the mean for each row
rand_array.mean(axis = 1)

array([-0.1383677 , -0.90577197])

In [50]:
# compute the mean for each column
rand_array.mean(axis = 0)

array([ 0.15984889, -1.07965881, -0.52190047, -1.09210441, -0.07653439])

In [51]:
rand_array.sum()

-5.220698369064269

In [52]:
rand_array.sum(axis = 1)

array([-0.69183852, -4.52885985])

In [56]:
np.median(rand_array, axis = 1)

array([ 0.04653009, -1.09033103])

In [58]:
sorted = np.array(rand_array)

sorted.sort()

print(rand_array)
print("sorted")
print(sorted)

[[ 0.55824343 -1.06048698  0.04653009 -0.72257849  0.48645344]
 [-0.23854565 -1.09883063 -1.09033103 -1.46163033 -0.63952221]]
sorted
[[-1.06048698 -0.72257849  0.04653009  0.48645344  0.55824343]
 [-1.46163033 -1.09883063 -1.09033103 -0.63952221 -0.23854565]]


In [60]:
!echo "$sorted"

[[-1.06048698 -0.72257849  0.04653009  0.48645344  0.55824343]
 [-1.46163033 -1.09883063 -1.09033103 -0.63952221 -0.23854565]]


In [64]:
s1 = np.array(['ehab', 'mohamed', 'ali'])
s2 = np.array(['try', 'mohamed', 'samir'])

print(np.intersect1d(s1, s2))

['mohamed']


In [65]:
print(np.union1d(s1, s2))

['ali' 'ehab' 'mohamed' 'samir' 'try']


In [66]:
print(np.setdiff1d(s1, s2))

['ali' 'ehab']


In [67]:
print(np.in1d(s1, s2))

[False  True False]


In [69]:
ar1 = np.zeros((10,5))

ar1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [71]:
ar2 = np.array([[1, 2, 3, 4, 5]])

ar1 + ar2

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])